swagger: '2.0'
info:
  title: SMS Linked Data API
  description: A set of Linked Data powered APIs for Semantically Mapping Science (SMS)
  version: "1.0"
# the domain of the service
host: sms.risis.eu
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /geo.pointToNUTS;lat={latitude};long={longitude}:
    get:
      summary: given a point, returns the NUTS boundaries.
      description: |
        Receives Longitude and Latitude of a point and returns its NUTS containers in different levels.
      parameters:
        - name: latitude
          in: path
          description: Latitude of the given point.
          required: true
          type: number
          format: double
        - name: longitude
          in: path
          description: Longitude of the given point.
          required: true
          type: number
          format: double
      tags:
        - Geo-Services
      responses:
        200:
          description: An array of object with corresponding NUTS details.
          schema:
            type: array
            items:
              $ref: '#/definitions/pointToNUTS'
  /geo.NUTStoName;code={code}:
    get:
      summary: given a NUTS code, returns the name of the NUTS region.
      parameters:
        - name: code
          in: path
          description: code for NUTS region
          required: true
          type: string
      tags:
        - Geo-Services
      responses:
        200:
          description: An array of object with corresponding NUTS details.
          schema:
            type: array
            items:
              $ref: '#/definitions/NUTStoName'
  /geo.NameToNUTS;name={name}:
    get:
      summary: given a NUTS region name, returns the code and details of the NUTS region.
      parameters:
        - name: name
          in: path
          description: name of NUTS region
          required: true
          type: string
      tags:
        - Geo-Services
      responses:
        200:
          description: An array of object with corresponding NUTS details.
          schema:
            type: array
            items:
              $ref: '#/definitions/NameToNUTS'
  /geo.NUTStoPolygon;code={code}:
    get:
      summary: given a NUTS code, returns the containing polygon shape and details of the NUTS region.
      parameters:
        - name: code
          in: path
          description: code for NUTS region
          required: true
          type: string
      tags:
        - Geo-Services
      responses:
        200:
          description: An array of object with corresponding NUTS details.
          schema:
            type: array
            items:
              $ref: '#/definitions/NUTStoPolygon'
  /metadata.dataset;name={name}:
    get:
      summary: given a dataset's name, returns the related metadata properties.
      description: |
        Returns all the metadata properties of a given dataset
      parameters:
        - name: name
          in: path
          description: Name of the dataset.
          required: true
          type: string
      tags:
        - Metadata-Services
      responses:
        200:
          description: An array of object with property details.
          schema:
            type: array
            items:
              $ref: '#/definitions/DatasetProperties'
  /metadata.datasetsList:
    get:
      summary: gives a list of RISIS datasets.
      description: |
        Returns a list of all available RISIS datasets.
      tags:
        - Metadata-Services
      responses:
        200:
          description: An array of object with datasets names and urls.
          schema:
            type: array
            items:
              $ref: '#/definitions/DatasetsList'
definitions:
  pointToNUTS:
    type: object
    properties:
      longitude:
        type: number
        format: double
      latitude:
        type: number
        format: double
      resources:
        type: array
        description: List of NUTS region.
        items:
           $ref: '#/definitions/NUTS'
  NameToNUTS:
    type: object
    properties:
      resources:
        type: array
        description: List of NUTS region.
        items:
           $ref: '#/definitions/NUTS'
  NUTStoName:
    type: object
    properties:
      resources:
        type: array
        description: List of NUTS region.
        items:
           $ref: '#/definitions/NUTS'
  NUTStoPolygon:
    type: object
    properties:
      resources:
        type: array
        description: List of NUTS region containg the their corresponding polygons.
        items:
           $ref: '#/definitions/NUTSP'
  NUTS:
    type: object
    properties:
      uri:
        type: string
      name:
        type: string
      code:
        type: string
      level:
        type: integer
  NUTSP:
    type: object
    properties:
      uri:
        type: string
      name:
        type: string
      code:
        type: string
      level:
        type: integer
      polygon:
        type: string
  DatasetsList:
    type: object
    properties:
      resources:
        type: array
        description: List of Datasets.
        items:
           $ref: '#/definitions/DatasetBrief'
  DatasetBrief:
    type: object
    properties:
      title:
        type: string
      name:
        type: string
      URL:
        type: string
      resourceURI:
        type: string
      resourceGraphName:
        type: string
  DatasetProperties:
    type: object
